-- test VIEW_USER_INFORMATION
SELECT * FROM jsoren.PUBLIC_USER_INFORMATION MINUS SELECT * FROM VIEW_USER_INFORMATION;

SELECT * FROM VIEW_USER_INFORMATION  MINUS SELECT * FROM jsoren.PUBLIC_USER_INFORMATION;

SELECT * FROM VIEW_USER_INFORMATION  INTERSECT SELECT * FROM jsoren.PUBLIC_USER_INFORMATION;
-- test VIEW_ARE_FRIENDS
SELECT * FROM jsoren.PUBLIC_ARE_FRIENDS MINUS SELECT * FROM VIEW_ARE_FRIENDS;

SELECT * FROM VIEW_ARE_FRIENDS MINUS SELECT * FROM jsoren.PUBLIC_ARE_FRIENDS;

-- test VIEW_ARE_FRIENDS
SELECT * FROM jsoren.PUBLIC_PHOTO_INFORMATION MINUS SELECT * FROM VIEW_PHOTO_INFORMATION; -- 1889

SELECT * FROM VIEW_PHOTO_INFORMATION MINUS SELECT * FROM jsoren.PUBLIC_PHOTO_INFORMATION; -- 0

SELECT * FROM jsoren.PUBLIC_EVENT_INFORMATION MINUS SELECT * FROM VIEW_EVENT_INFORMATION;

90	   85		1687	Mountains	21-DEC-69 02.00.00.000000 PM 05-JUN-26 03.00.00.000000 AM link everyone

select count(*) from(select FIRST_NAME from jsoren.PUBLIC_USER_INFORMATION minus select FIRST_NAME from VIEW_USER_INFORMATION);
select count(*) from(select LAST_NAME from jsoren.PUBLIC_USER_INFORMATION minus select LAST_NAME from VIEW_USER_INFORMATION);
select count(*) from(select YEAR_OF_BIRTH from jsoren.PUBLIC_USER_INFORMATION minus select YEAR_OF_BIRTH from VIEW_USER_INFORMATION);
select count(*) from(select MONTH_OF_BIRTH from jsoren.PUBLIC_USER_INFORMATION minus select MONTH_OF_BIRTH from VIEW_USER_INFORMATION);
select count(*) from(select PROGRAM_YEAR from jsoren.PUBLIC_USER_INFORMATION minus select PROGRAM_YEAR from VIEW_USER_INFORMATION);
select count(*) from(select PROGRAM_YEAR from jsoren.PUBLIC_USER_INFORMATION minus select PROGRAM_YEAR from VIEW_USER_INFORMATION);