CREATE TABLE USERS (
	USER_ID INTEGER,
	FIRST_NAME CHAR(100),
	LAST_NAME CHAR(100),
	YEAR_OF_BIRTH INTEGER,
	MONTH_OF_BIRTH INTEGER,
	DAY_OF_BIRTH INTEGER,
	GENDER CHAR(100),
	PRIMARY KEY (USER_ID)
);

CREATE TABLE FRIENDS (
	USER1_ID INTEGER,
	USER2_ID INTEGER,
	PRIMARY KEY (USER1_ID, USER2_ID),
	FOREIGN KEY (USER1_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
	FOREIGN KEY (USER2_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE CITIES (
	CITY_ID INTEGER,
	CITY_NAME CHAR(100),
	STATE_NAME CHAR(100),
	COUNTRY_NAME CHAR(100),
	PRIMARY KEY (CITY_ID),
	UNIQUE (CITY_NAME, STATE_NAME, COUNTRY_NAME)
);

CREATE TABLE USER_CURRENT_CITY (
	USER_ID INTEGER,
	CURRENT_CITY_ID INTEGER,
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
	FOREIGN KEY (CURRENT_CITY_ID) REFERENCES CITIES(CITY_ID) ON DELETE CASCADE
);

CREATE TABLE USER_HOMETOWN_CITY (
	USER_ID INTEGER,
	HOMETOWN_CITY_ID INTEGER,
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
	FOREIGN KEY (HOMETOWN_CITY_ID) REFERENCES CITIES(CITY_ID) ON DELETE CASCADE
);

CREATE TABLE PROGRAMS (
	PROGRAM_ID INTEGER,
	INSTITUTION CHAR(100),
	CONCENTRATION CHAR(100),
	DEGREE CHAR(100),
	PRIMARY KEY (PROGRAM_ID),
	UNIQUE (INSTITUTION, CONCENTRATION, DEGREE)
);

CREATE TABLE EDUCATION (
	USER_ID INTEGER,
	PROGRAM_ID INTEGER,
	PROGRAM_YEAR INTEGER,
	PRIMARY KEY (USER_ID, PROGRAM_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
	FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAMS(PROGRAM_ID) ON DELETE CASCADE
);


