--first delete child tables
DROP TABLE USER_CURRENT_CITY;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE EDUCATION;

DROP TABLE FRIENDS;

DROP TABLE Tags;
DROP TABLE Messages;
ALTER TABLE Albums DROP CONSTRAINT "COVER_PHOTO_CONSTRAINT";
ALTER TABLE Albums DROP COLUMN cover_photo_id;
DROP TABLE Photos;
DROP TABLE Albums;

DROP TABLE PARTICIPANTS;
DROP TABLE Events;

-- then, delete parent tables (or we can use CASCADE CONSTRAINTS )
DROP SEQUENCE seq1;
DROP SEQUENCE seq2;

DROP TRIGGER add_city_id;
DROP TABLE CITIES;

DROP TRIGGER add_program_id;
DROP TABLE PROGRAMS;

DROP TABLE USERS;









