-- first, delete children table
DROP TABLE FRIENDS;

DROP TABLE USER_CURRENT_CITY;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE EDUCATION;

-- then, delete parent tables (or we can use CASCADE CONSTRAINTS )
DROP TABLE USERS;

DROP TABLE CITIES;

DROP TABLE PROGRAMS;

