-- first, delete children table
DROP TABLE FRIENDS;

DROP TABLE USER_CURRENT_CITY;

DROP TABLE USER_HOMETOWN_CITY;

DROP TABLE EDUCATION;

DROP TABLE Tags;
ALTER TABLE Albums DROP CONSTRAINT "COVER_PHOTO_CONSTRAINT";
DROP TABLE Messages;
DROP TABLE Photos;
DROP TABLE Albums;

DROP TABLE PARTICIPANTS;
DROP TABLE Events;

-- then, delete parent tables (or we can use CASCADE CONSTRAINTS )
DROP TABLE USERS;

DROP TABLE CITIES;

DROP TABLE PROGRAMS;





