-- CREATE SEQUENCE sequence seq1
-- 	START WITH 1
-- 	INCREMENT BY 1;


-- CREATE TRIGGER trigger name
-- 	BEFORE INSERT ON table name
-- 		FOR EACH ROW
-- 			BEGIN
-- 				SELECT seq1.NEXTVAL INTO :NEW.id field FROM DUAL;
-- 			END;
-- /


INSERT INTO USERS(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
SELECT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER
FROM PUBLIC_USER_INFORMATION