-- test VIEW_USER_INFORMATION
SELECT * FROM jsoren.PUBLIC_USER_INFORMATION MINUS SELECT * FROM VIEW_USER_INFORMATION;

SELECT * FROM VIEW_USER_INFORMATION  MINUS SELECT * FROM jsoren.PUBLIC_USER_INFORMATION;

SELECT * FROM VIEW_USER_INFORMATION  INTERSECT SELECT * FROM jsoren.PUBLIC_USER_INFORMATION;
-- test VIEW_ARE_FRIENDS
SELECT * FROM jsoren.PUBLIC_ARE_FRIENDS MINUS SELECT * FROM VIEW_ARE_FRIENDS;

SELECT * FROM VIEW_ARE_FRIENDS MINUS SELECT * FROM jsoren.PUBLIC_ARE_FRIENDS;

-- test VIEW_ARE_FRIENDS
SELECT * FROM jsoren.PUBLIC_PHOTO_INFORMATION MINUS SELECT * FROM VIEW_PHOTO_INFORMATION; -- 1889

SELECT * FROM VIEW_PHOTO_INFORMATION MINUS SELECT * FROM jsoren.PUBLIC_PHOTO_INFORMATION; -- 0

