-- Test query 3: 756 rows selected; identical to solution
-- SELECT u.USER_ID, FIRST_NAME, LAST_NAME FROM
-- jiaqni.PUBLIC_USERS u, jiaqni.PUBLIC_USER_CURRENT_CITY ct, jiaqni.PUBLIC_USER_HOMETOWN_CITY ht
-- WHERE u.USER_ID = ct.USER_ID AND
-- ct.USER_ID = ht.USER_ID AND 
-- HOMETOWN_CITY_ID <> CURRENT_CITY_ID 
-- ORDER BY USER_ID;


javac project2/FakebookOracle.java project2/MyFakebookOracle.java  project2/TestFakebookOracle.java project2/TestFakebookOracleFull.java
java -Xmx64M -cp "project2/ojdbc6.jar:" project2/TestFakebookOracle
java -Xmx64M -cp "project2/ojdbc6.jar:" project2/TestFakebookOracleFull

-- Test query 4:
-- CREATE VIEW VIEW_QUERY4 AS
-- SELECT x.TAG_PHOTO_ID, x.NUM_TAGGED, p.ALBUM_ID, a.ALBUM_NAME, p.PHOTO_CAPTION, p.PHOTO_LINK
-- FROM (SELECT t.TAG_PHOTO_ID, COUNT(TAG_SUBJECT_ID) AS NUM_TAGGED
-- 		FROM jiaqni.PUBLIC_TAGS t
-- 		GROUP BY t.TAG_PHOTO_ID
-- 		ORDER BY NUM_TAGGED DESC, t.TAG_PHOTO_ID) x, jiaqni.PUBLIC_PHOTOS p, jiaqni.PUBLIC_ALBUMS a
-- WHERE x.TAG_PHOTO_ID = p.PHOTO_ID
-- AND p.ALBUM_ID = a.ALBUM_ID
-- AND ROWNUM <= 5;


-- SELECT DISTINCT u.USER_ID, u.FIRST_NAME, u.LAST_NAME
-- FROM VIEW_QUERY4 v, jiaqni.PUBLIC_TAGS t, jiaqni.PUBLIC_USERS u
-- WHERE v.TAG_PHOTO_ID = t.TAG_PHOTO_ID
-- AND t.TAG_SUBJECT_ID = u.USER_ID;


-- Test query 5:
-- DROP VIEW VIEW_QUERY5;

-- CREATE VIEW VIEW_QUERY5 AS
-- SELECT DISTINCT u1.USER_ID USER1_ID, u1.FIRST_NAME USER1_FIRST_NAME, u1.LAST_NAME USER1_LAST_NAME, u1.YEAR_OF_BIRTH USER1_YEAR_OF_BIRTH, u2.USER_ID USER2_ID, u2.FIRST_NAME USER2_FIRST_NAME, u2.LAST_NAME USER2_LAST_NAME, u2.YEAR_OF_BIRTH USER2_YEAR_OF_BIRTH
-- 	FROM FRIENDS f, USERS u1, USERS u2, TAGS t1, TAGS t2
-- 	WHERE u1.USER_ID < u2.USER_ID
-- 	AND u1.USER_ID = t1.TAG_SUBJECT_ID
-- 	AND u2.USER_ID = t2.TAG_SUBJECT_ID
-- 	AND t1.TAG_PHOTO_ID = t2.TAG_PHOTO_ID
-- 	AND u1.GENDER = u2.GENDER
-- 	AND u1.YEAR_OF_BIRTH - u2.YEAR_OF_BIRTH <= 5
-- 	AND ((f.USER1_ID = u1.USER_ID AND f.USER2_ID != u2.USER_ID) OR (f.USER2_ID = u2.USER_ID AND f.USER1_ID != u1.USER_ID)); 

-- SELECT COUNT(*) FROM VIEW_QUERY5;

-- export sql to excel
-- SET PAGESIZE 50000;
-- SET MARKUP HTML ON SPOOL ON;
-- SET NUM 24;
-- SPOOL VIEW_QUERY5.xls;
-- SELECT * from VIEW_QUERY5;
-- SPOOL OFF;
-- SET MARKUP HTML OFF SPOOL OFF;


 -- approach 1
DROP VIEW VIEW_QUERY5;
DROP VIEW VIEW_QUERY5_2;

-- CREATE VIEW VIEW_QUERY5 AS
SELECT x.USER1_ID, x.USER1_FIRST_NAME, x.USER1_LAST_NAME, x.USER1_YEAR_OF_BIRTH, x.USER2_ID, x.USER2_FIRST_NAME, x.USER2_LAST_NAME, x.USER2_YEAR_OF_BIRTH, COUNT(*) NUM_SHARED_PHOTOS
FROM (SELECT DISTINCT u1.USER_ID USER1_ID, u1.FIRST_NAME USER1_FIRST_NAME, u1.LAST_NAME USER1_LAST_NAME, u1.YEAR_OF_BIRTH USER1_YEAR_OF_BIRTH, u2.USER_ID USER2_ID, u2.FIRST_NAME USER2_FIRST_NAME, u2.LAST_NAME USER2_LAST_NAME, u2.YEAR_OF_BIRTH USER2_YEAR_OF_BIRTH
	FROM jiaqni.PUBLIC_FRIENDS f, jiaqni.PUBLIC_USERS u1, jiaqni.PUBLIC_USERS u2, jiaqni.PUBLIC_TAGS t1, jiaqni.PUBLIC_TAGS t2
	WHERE u1.USER_ID = t1.TAG_SUBJECT_ID
	AND u2.USER_ID = t2.TAG_SUBJECT_ID
	AND t1.TAG_PHOTO_ID = t2.TAG_PHOTO_ID
	AND u1.GENDER = u2.GENDER
	AND ABS(u1.YEAR_OF_BIRTH - u2.YEAR_OF_BIRTH) <= 2
	-- There are 4 cases
	AND u1.USER_ID < u2.USER_ID
	AND ((f.USER1_ID = u1.USER_ID AND f.USER2_ID != u2.USER_ID) OR (f.USER2_ID = u2.USER_ID AND f.USER1_ID != u1.USER_ID)) ) x, jiaqni.PUBLIC_TAGS t3, jiaqni.PUBLIC_TAGS t4
WHERE x.USER1_ID = t3.TAG_SUBJECT_ID
AND x.USER2_ID = t4.TAG_SUBJECT_ID
AND t3.TAG_PHOTO_ID = t4.TAG_PHOTO_ID
AND ROWNUM <= 5
GROUP BY x.USER1_ID, x.USER1_FIRST_NAME, x.USER1_LAST_NAME, x.USER1_YEAR_OF_BIRTH, x.USER2_ID, x.USER2_FIRST_NAME, x.USER2_LAST_NAME, x.USER2_YEAR_OF_BIRTH
ORDER BY NUM_SHARED_PHOTOS DESC, USER1_ID, USER2_ID;

-- approach 2

-- CREATE VIEW VIEW_QUERY5 AS
-- SELECT DISTINCT u1.USER_ID USER1_ID, u1.FIRST_NAME USER1_FIRST_NAME, u1.LAST_NAME USER1_LAST_NAME, u1.YEAR_OF_BIRTH USER1_YEAR_OF_BIRTH, u2.USER_ID USER2_ID, u2.FIRST_NAME USER2_FIRST_NAME, u2.LAST_NAME USER2_LAST_NAME, u2.YEAR_OF_BIRTH USER2_YEAR_OF_BIRTH, COUNT(DISTINCT t1.TAG_SUBJECT_ID) NUM_SHARED_PHOTOS
-- FROM jiaqni.PUBLIC_FRIENDS f, jiaqni.PUBLIC_USERS u1, jiaqni.PUBLIC_USERS u2, jiaqni.PUBLIC_TAGS t1, jiaqni.PUBLIC_TAGS t2
-- WHERE u1.USER_ID = t1.TAG_SUBJECT_ID
-- AND u2.USER_ID = t2.TAG_SUBJECT_ID
-- AND t1.TAG_PHOTO_ID = t2.TAG_PHOTO_ID
-- AND u1.GENDER = u2.GENDER
-- AND ABS(u1.YEAR_OF_BIRTH - u2.YEAR_OF_BIRTH) <= 2
-- -- There are 4 cases
-- AND u1.USER_ID < u2.USER_ID
-- AND ((f.USER1_ID = u1.USER_ID AND f.USER2_ID != u2.USER_ID) OR (f.USER2_ID = u2.USER_ID AND f.USER1_ID != u1.USER_ID))
-- AND ROWNUM <= 5
-- GROUP BY u1.USER_ID, u1.FIRST_NAME, u1.LAST_NAME, u1.YEAR_OF_BIRTH, u2.USER_ID, u2.FIRST_NAME, u2.LAST_NAME, u2.YEAR_OF_BIRTH
-- ORDER BY NUM_SHARED_PHOTOS DESC, USER1_ID, USER2_ID;



export sql to excel
SET PAGESIZE 50000;
SET MARKUP HTML ON SPOOL ON;
SET NUM 24;
SPOOL VIEW_QUERY5.xls;
SELECT * from VIEW_QUERY5;
SPOOL OFF;
SET MARKUP HTML OFF SPOOL OFF;

CREATE VIEW VIEW_QUERY5_2 AS
SELECT DISTINCT x.USER1_ID, x.USER2_ID, p.PHOTO_ID, p.ALBUM_ID, a.ALBUM_NAME, p.PHOTO_CAPTION, p.PHOTO_LINK
FROM VIEW_QUERY5 x, jiaqni.PUBLIC_TAGS t1, jiaqni.PUBLIC_TAGS t2, jiaqni.PUBLIC_PHOTOS p, jiaqni.PUBLIC_ALBUMS a
WHERE x.USER1_ID = t1.TAG_SUBJECT_ID
AND x.USER2_ID = t2.TAG_SUBJECT_ID
AND t1.TAG_PHOTO_ID = t2.TAG_PHOTO_ID
AND t1.TAG_PHOTO_ID = p.PHOTO_ID
AND p.ALBUM_ID = a.ALBUM_ID
ORDER BY x.USER1_ID, x.USER2_ID;

export sql to excel
SET PAGESIZE 50000;
SET MARKUP HTML ON SPOOL ON;
SET NUM 24;
SPOOL VIEW_QUERY5_2.xls;
SELECT * from VIEW_QUERY5_2;
SPOOL OFF;
SET MARKUP HTML OFF SPOOL OFF;

-- SELECT p.PHOTO_ID, t.TAG_SUBJECT_ID FROM jiaqni.PUBLIC_PHOTOS p, jiaqni.PUBLIC_TAGS t WHERE p.PHOTO_ID = t.TAG_PHOTO_ID AND p.PHOTO_ID = 1159; 
-- SELECT p.PHOTO_ID, t.TAG_SUBJECT_ID FROM jiaqni.PUBLIC_PHOTOS p, jiaqni.PUBLIC_TAGS t WHERE p.PHOTO_ID = t.TAG_PHOTO_ID AND p.PHOTO_ID = 1310; 
-- SELECT p.PHOTO_ID, t.TAG_SUBJECT_ID FROM jiaqni.PUBLIC_PHOTOS p, jiaqni.PUBLIC_TAGS t WHERE p.PHOTO_ID = t.TAG_PHOTO_ID AND p.PHOTO_ID = 429; 



-- Test query 9
-- SELECT f.USER1_ID, f.USER2_ID
-- FROM jiaqni.PUBLIC_FRIENDS f, jiaqni.PUBLIC_USERS u1, jiaqni.PUBLIC_USERS u2, jiaqni.PUBLIC_USER_HOMETOWN_CITY ht1, jiaqni.PUBLIC_USER_HOMETOWN_CITY ht2
-- WHERE f.USER1_ID = u1.USER_ID
-- AND f.USER2_ID = u2.USER_ID
-- AND u1.USER_ID = ht1.USER_ID
-- AND u2.USER_ID = ht2.USER_ID
-- AND u1.USER_ID < u2.USER_ID
-- AND u1.LAST_NAME = u2.LAST_NAME
-- AND ht1.HOMETOWN_CITY_ID = ht2.HOMETOWN_CITY_ID
-- AND ABS(u1.YEAR_OF_BIRTH - u2.YEAR_OF_BIRTH) < 10
-- ORDER BY f.USER1_ID, f.USER2_ID;


-- export sql to excel
-- SET PAGESIZE 50000;
-- SET MARKUP HTML ON SPOOL ON;
-- SET NUM 24;
-- SPOOL VIEW_QUERY4.xls;
-- SELECT * from VIEW_QUERY4;
-- SPOOL OFF;
-- SET MARKUP HTML OFF SPOOL OFF;